jdbc:
  dbProvider: postgresql
  port: 5432
  host: localhost # if your DB is running on a different machine, change this to its domain or IP
  schema: budget
  user: budget
  password: budget

server:
  port: 8080
