name: publish-budget-server-container.yml
on:
  - workflow_dispatch

jobs:
  publish-test-db-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Container
        run: |
          cd ci/server
          docker build . --tag ghcr.io/benjishults/budget-server:latest
          #          docker run ghcr.io/benjishults/postgres-test:latest
          docker push ghcr.io/benjishults/budget-server:latest
